"""add difficulty and image_style to levels table

Revision ID: 1c448f91e9b9
Revises: dba6da0fba12
Create Date: 2026-03-07 10:00:22.695616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c448f91e9b9'
down_revision: Union[str, Sequence[str], None] = 'dba6da0fba12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('difficulty', sa.Integer(), nullable=False))
    op.add_column('levels', sa.Column('sprite_style', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_levels_difficulty'), 'levels', ['difficulty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_levels_difficulty'), table_name='levels')
    op.drop_column('levels', 'sprite_style')
    op.drop_column('levels', 'difficulty')
    # ### end Alembic commands ###
