"""restructure level token usage

Revision ID: 2c916252d2d9
Revises: 1c448f91e9b9
Create Date: 2026-03-07 11:41:47.550968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c916252d2d9'
down_revision: Union[str, Sequence[str], None] = '1c448f91e9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_token_usage', sa.Column('usage_type', sa.String(), nullable=False))
    op.add_column('level_token_usage', sa.Column('tokens', sa.Integer(), nullable=False))
    op.add_column('level_token_usage', sa.Column('minutes', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_level_token_usage_level_id'), table_name='level_token_usage')
    op.create_index(op.f('ix_level_token_usage_level_id'), 'level_token_usage', ['level_id'], unique=False)
    op.drop_column('level_token_usage', 'generation_tokens')
    op.drop_column('level_token_usage', 'repair_tokens')
    op.drop_column('level_token_usage', 'total_tokens')
    op.drop_column('level_token_usage', 'repair_count')
    op.drop_column('level_token_usage', 'sprite_tokens')
    op.drop_column('level_token_usage', 'validation_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_token_usage', sa.Column('validation_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_token_usage', sa.Column('sprite_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_token_usage', sa.Column('repair_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_token_usage', sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_token_usage', sa.Column('repair_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('level_token_usage', sa.Column('generation_tokens', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_level_token_usage_level_id'), table_name='level_token_usage')
    op.create_index(op.f('ix_level_token_usage_level_id'), 'level_token_usage', ['level_id'], unique=True)
    op.drop_column('level_token_usage', 'minutes')
    op.drop_column('level_token_usage', 'tokens')
    op.drop_column('level_token_usage', 'usage_type')
    # ### end Alembic commands ###
