"""create favorite levels table

Revision ID: 8b6ab605f755
Revises: 069aee2b2a2b
Create Date: 2026-02-22 17:44:27.723158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b6ab605f755'
down_revision: Union[str, Sequence[str], None] = '069aee2b2a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_levels',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level_id', name='uq_favorite_levels_user_level')
    )
    op.create_index(op.f('ix_favorite_levels_level_id'), 'favorite_levels', ['level_id'], unique=False)
    op.create_index('ix_favorite_levels_level_user', 'favorite_levels', ['level_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_favorite_levels_user_id'), 'favorite_levels', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_levels_user_id'), table_name='favorite_levels')
    op.drop_index('ix_favorite_levels_level_user', table_name='favorite_levels')
    op.drop_index(op.f('ix_favorite_levels_level_id'), table_name='favorite_levels')
    op.drop_table('favorite_levels')
    # ### end Alembic commands ###
