"""create level ratings table

Revision ID: aeac0150ec67
Revises: f133c4f3b48a
Create Date: 2026-02-22 15:47:46.076541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeac0150ec67'
down_revision: Union[str, Sequence[str], None] = 'f133c4f3b48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_level_ratings_rating_1_5'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'level_id', name='uq_level_ratings_user_level')
    )
    op.create_index(op.f('ix_level_ratings_level_id'), 'level_ratings', ['level_id'], unique=False)
    op.create_index('ix_level_ratings_level_id_user_id', 'level_ratings', ['level_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_level_ratings_user_id'), 'level_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_level_ratings_user_id'), table_name='level_ratings')
    op.drop_index('ix_level_ratings_level_id_user_id', table_name='level_ratings')
    op.drop_index(op.f('ix_level_ratings_level_id'), table_name='level_ratings')
    op.drop_table('level_ratings')
    # ### end Alembic commands ###
