"""create level token usage table

Revision ID: dba6da0fba12
Revises: 76856e415f08
Create Date: 2026-03-06 14:06:35.035133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba6da0fba12'
down_revision: Union[str, Sequence[str], None] = '76856e415f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_token_usage',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('generation_tokens', sa.Integer(), nullable=False),
    sa.Column('validation_tokens', sa.Integer(), nullable=False),
    sa.Column('repair_tokens', sa.Integer(), nullable=False),
    sa.Column('sprite_tokens', sa.Integer(), nullable=False),
    sa.Column('repair_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_level_token_usage_level_id'), 'level_token_usage', ['level_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_level_token_usage_level_id'), table_name='level_token_usage')
    op.drop_table('level_token_usage')
    # ### end Alembic commands ###
