"""create levels table

Revision ID: f133c4f3b48a
Revises: 2a7bf8aa5fec
Create Date: 2026-02-21 22:39:16.410049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f133c4f3b48a'
down_revision: Union[str, Sequence[str], None] = '2a7bf8aa5fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('sucessfull_level_generation', sa.Boolean(), nullable=False),
    sa.Column('sucessfull_sprite_generation', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_story'), 'levels', ['story'], unique=False)
    op.create_index(op.f('ix_levels_title'), 'levels', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_levels_title'), table_name='levels')
    op.drop_index(op.f('ix_levels_story'), table_name='levels')
    op.drop_table('levels')
    # ### end Alembic commands ###
